global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'machine-vm'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'metrics-gateway'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['metrics-gateway:9091']

  - job_name: 'zowe-metrics-server'

    scrape_interval: 10s
    scrape_timeout: 5s

    scheme: https
    tls_config:
      insecure_skip_verify: true

    static_configs:
      - targets: ['<server-host>:19000']
      # - targets: ['vm30101.svl.ibm.com:19000']
      # - targets: ['zzow01.zowe.marist.cloud:19000']
