server:
  http:
    enabled: true
    port: 19001
  https:
    enabled: true
    port: 19000
    key: sslcert/server.key
    cert: sslcert/server.cert
metrics:
  - name: sdsf.sys
    # estimated overhead 0.7%
    worker: shell
    options:
      interval: 10
      # command base dir is "src/collectors"
      command: metrics/sysagg.rexx
      outputFormat: json
  - name: sdsf.da
    # estimated overhead 0.8%
    worker: shell
    options:
      interval: 10
      # command base dir is "src/collectors"
      command: metrics/da.rexx
      outputFormat: json
