env:
  es6: true
  node: true
#   jest: true
root: true
plugins:
- '@typescript-eslint'
extends:
- eslint:recommended
- 'plugin:@typescript-eslint/eslint-recommended'
- 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
