cadvisor:
  image: google/cadvisor
  ports:
    - 8080:8080
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro

metrics-gateway:
  image: prom/pushgateway
  ports:
    - 9091:9091

prometheus-server:
  image: prom/prometheus
  ports:
    - 9090:9090
  links:
    - cadvisor:cadvisor
    - metrics-gateway:metrics-gateway
    - zms:zms
  volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

grafana-ui:
  image: grafana/grafana
  ports:
    - 3000:3000
  environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
  links:
    - prometheus-server:prometheus

zms:
  image: jackjiaibm/zowe-metrics-server
  ports:
    - 19000:19000
    - 19001:19001
  environment:
    - RMF_DDS_PROTOCOL=https
    - RMF_DDS_HOST=<your-rmf-dds-server>
    - RMF_DDS_PORT=8803
    - RMF_DDS_USERNAME=jack
    - RMF_DDS_PASSWORD=beanstlk
