name: SPDX SBOM Generation

on:
  workflow_dispatch:

env:
  ZOWE_RELEASE_BRANCH: rc
  REPORT_DIR: reports

jobs:

  cli-package-sbom:

    env:
      BASE_CLI_DIR: cli_explode
      UPLOAD_DIR: "/tmp/zowe_cli"
      UPLOAD_NAME: "Zowe CLI Standalone"

    runs-on: ubuntu-latest
    name: "Build Zowe CLI Standalone Package SBOM"

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Build docker container
        run: |
          cd .dockerfiles
          docker build -t zowe/local-fossology:latest -f spdxsbom.Dockerfile .
      - name: Install Python3, Pip, Pre-Reqs
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip unzip
      - name: Download and extract Zowe CLI Package
        run: |
          mkdir -p ${{ env.BASE_CLI_DIR }}
          cd ${{ env.BASE_CLI_DIR }}
          wget https://zowe.jfrog.io/artifactory/libs-release-local/org/zowe/1.27.2/zowe-cli-package-1.27.2.zip -O zowe_cli.zip
          unzip zowe_cli.zip
          rm zowe_cli.zip
      - name: Run Fossology Docker image
        run: docker run -d -v $GITHUB_WORKSPACE/${{ env.BASE_CLI_DIR }}:${{ env.UPLOAD_DIR }} -p 8081:80 zowe/local-fossology:latest
      - name: Wait for Fossology to start
        run: wget http://localhost:8081/
      - name: Run Scans
        run: |
          mkdir -p $GITHUB_WORKSPACE/${{ env.REPORT_DIR }}
          cd $GITHUB_WORKSPACE/licenses/sbom
          pip3 install -r requirements.txt
          ZOWE_SOURCES_VERSION=${{ env.ZOWE_RELEASE_BRANCH }} OUTPUT_DIR=$GITHUB_WORKSPACE/${{ env.REPORT_DIR }} python3 fossology/local.py
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.REPORT_DIR }}/*

  pax-sbom:
    env:
      ZIP_REPO_BASE_DIR: zip
      ZDS_REPO_BASE_DIR: zds
      PAX_BASE_DIR: zowe_pax
      PAX_CONV_DIR: zowe_pax_conv
      UPLOAD_DIR: "/tmp/zowe_pax"
      UPLOAD_NAME: "Zowe Pax"
  
    runs-on: ubuntu-latest
    name: "Build Zowe PAX SPDX SBOM"
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: ${{ env.ZDS_REPO_BASE_DIR }}
      - name: Checkout zowe-install-packaging (for autoconv)
        uses: actions/checkout@v2
        with:
          repository: "zowe/zowe-install-packaging"
          ref: ${{ env.ZOWE_RELEASE_BRANCH }}
          path: ${{ env.ZIP_REPO_BASE_DIR }}
      - name: Build docker container
        run: |
          cd $ZDS_REPO_BASE_DIR/.dockerfiles
          docker build -t zowe/local-fossology:latest -f spdxsbom.Dockerfile .
      - name: Download and extract Zowe PAX
        run: |
          mkdir -p ${{ env.PAX_BASE_DIR }}
          cd ${{ env.PAX_BASE_DIR }}
          wget https://zowe.jfrog.io/artifactory/libs-release-local/org/zowe/2.0.0-TP2/zowe-2.0.0-TP2.pax -O zowe.pax
          tar -xvf zowe.pax
          rm zowe.pax
      - name: Convert Zowe Pax
        run: |
          cd ${{ env.ZIP_REPO_BASE_DIR }}/containers/utils/autoconv/
          npm install
          npm run build
          ./bin/autoconv $GITHUB_WORKSPACE/${{ env.PAX_BASE_DIR }} $GITHUB_WORKSPACE/${{ env.PAX_CONV_DIR }}
      - name: Run Fossology Docker image
        run: docker run -d -p 8081:80 -v $GITHUB_WORKSPACE/${{ env.PAX_CONV_DIR }}/zowe_pax:/tmp/zowe_pax zowe/local-fossology:latest
      - name: Install Python3 and Pip
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip
      - name: Wait for Fossology to start
        run: wget http://localhost:8081/
      - name: Run Scans
        run: |
          cd ${{ env.ZDS_REPO_BASE_DIR }}/licenses/sbom
          pip3 install -r requirements.txt
          mkdir -p $GITHUB_WORKSPACE/${{ env.REPORT_DIR }}
          OUTPUT_DIR=$GITHUB_WORKSPACE/${{ env.REPORT_DIR }} python3 fossology/local.py
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zowe-pax.spdx
          path: ${{ env.REPORT_DIR }}/zowe-pax.spdx

  sources-sbom:
    runs-on: ubuntu-latest
    name: "Build Zowe Source SPDX SBOM"
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Build docker container
        run: |
          cd .dockerfiles
          docker build -t zowe/local-fossology:latest -f spdxsbom.Dockerfile .
      - name: Run Fossology Docker image
        run: docker run -d -p 8081:80 zowe/local-fossology:latest
      - name: Install Python3 and Pip
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip
      - name: Wait for Fossology to start
        run: wget http://localhost:8081/
      - name: Run Scans
        run: |
          mkdir -p $GITHUB_WORKSPACE/${{ env.REPORT_DIR }}
          cd $GITHUB_WORKSPACE/licenses/sbom
          pip3 install -r requirements.txt
          ZOWE_SOURCES_VERSION=${{ env.ZOWE_RELEASE_BRANCH }} OUTPUT_DIR=$GITHUB_WORKSPACE/${{ env.REPORT_DIR }} python3 fossology/sources.py
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.REPORT_DIR }}/*
