name: SPDX SBOM Generation

on:
  workflow_dispatch:
    inputs:
      zowe_artifacts_version: 
        description: "The version of the Zowe deliverables used in binary scanning. This is the version in 'libs-release-local'"
        required: true
        default: 2.0.0-TP2
      zowe_sources_branch: 
        description: "The branch of zowe-install-packaging used to determine sources included in the scan"
        required: true
        default: "v2.x/staging" 

env:
  ZOWE_RELEASE_BRANCH: ${{ github.event.inputs.zowe_sources_branch }}
  ZOWE_ARTIFACTS_VERSION: ${{ github.event.inputs.zowe_artifacts_version }}
  REPORT_DIR: reports

jobs:

  artifact-sboms:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - ARTIFACT_NAME: "Zowe CLI Standalone Package"
            ARTIFACT_LOCATION: https://zowe.jfrog.io/artifactory/libs-release-local/org/zowe/${{env.ZOWE_ARTIFACTS_VERSION}}/zowe-cli-package-${{env.ZOWE_ARTIFACTS_VERSION}}.zip
            EXPLODE: unzip
          - ARTIFACT_NAME: "Zowe PAX"
            ARTIFACT_LOCATION: https://zowe.jfrog.io/artifactory/libs-release-local/org/zowe/${{env.ZOWE_ARTIFACTS_VERSION}}/zowe-${{env.ZOWE_ARTIFACTS_VERSION}}.pax
            EXPLODE: tar -xf 
            CONVERT: True
          - ARTIFACT_NAME: "Zowe Containerization"
            ARTIFACT_LOCATION: https://zowe.jfrog.io/artifactory/libs-release-local/org/zowe/${{env.ZOWE_ARTIFACTS_VERSION}}/zowe-containerization-${{env.ZOWE_ARTIFACTS_VERSION}}.zip
            EXPLODE: unzip
    env:
      WORK_DIR: work
      MOUNT_POINT: /tmp/zowe_mount
    name: "SBOM: ${{ matrix.ARTIFACT_NAME}}"

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Build docker container
        run: |
          cd .dockerfiles
          docker build -t zowe/local-fossology:latest -f spdxsbom.Dockerfile .
      - name: Install Python3, Pip, Pre-Reqs
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip unzip
      - name: Download and extract ${{ matrix.ARTIFACT_NAME }}
        run: |
          mkdir -p ${{ env.WORK_DIR }}
          cd ${{ env.WORK_DIR }}
          wget ${{ matrix.ARTIFACT_LOCATION }} -O artifact.archive
          ${{ matrix.EXPLODE }} artifact.archive
          rm artifact.archive
      - if: ${{ matrix.CONVERT == True }}
        name: Checkout zowe-install-packaging (for autoconv)
        uses: actions/checkout@v2
        with:
          repository: "zowe/zowe-install-packaging"
          ref: ${{ env.ZOWE_RELEASE_BRANCH }}
          path: zip
      - if: ${{ matrix.CONVERT == True }}
        name: Run autoconv
        run: |
          mkdir -p conv_dir
          cd zip/containers/utils/autoconv/
          npm install
          npm run build
          mkdir $GITHUB_WORKSPACE/convert
          ./bin/autoconv $GITHUB_WORKSPACE/${{ env.WORK_DIR }} $GITHUB_WORKSPACE/convert
          rm -rf $GITHUB_WORKSPACE/${{ env.WORK_DIR }}
          mv  $GITHUB_WORKSPACE/convert/${{ env.WORK_DIR }} $GITHUB_WORKSPACE/${{ env.WORK_DIR }}
      - name: Run Fossology Docker image
        run: docker run -d -v $GITHUB_WORKSPACE/${{ env.WORK_DIR }}:${{ env.MOUNT_POINT }} -p 8081:80 zowe/local-fossology:latest
      - name: Wait for Fossology to start
        run: wget http://localhost:8081/
      - name: Run Scans
        run: |
          mkdir -p $GITHUB_WORKSPACE/${{ env.REPORT_DIR }}
          cd $GITHUB_WORKSPACE/licenses/sbom
          pip3 install -r requirements.txt
          UPLOAD_DIR=${{ env.MOUNT_POINT}} UPLOAD_NAME=${{ matrix.ARTIFACT_NAME }} OUTPUT_DIR=$GITHUB_WORKSPACE/${{ env.REPORT_DIR }} python3 fossology/local.py
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.ARTIFACT_NAME }}
          path: ${{ env.REPORT_DIR }}/*

  sources-sbom:
    runs-on: ubuntu-latest
    name: "Build Zowe Source SPDX SBOM"
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
      - name: Build docker container
        run: |
          cd .dockerfiles
          docker build -t zowe/local-fossology:latest -f spdxsbom.Dockerfile .
      - name: Run Fossology Docker image
        run: docker run -d -p 8081:80 zowe/local-fossology:latest
      - name: Install Python3 and Pip
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip
      - name: Wait for Fossology to start
        run: wget http://localhost:8081/
      - name: Run Scans
        run: |
          mkdir -p $GITHUB_WORKSPACE/${{ env.REPORT_DIR }}
          cd $GITHUB_WORKSPACE/licenses/sbom
          pip3 install -r requirements.txt
          ZOWE_SOURCES_VERSION=${{ env.ZOWE_RELEASE_BRANCH }} OUTPUT_DIR=$GITHUB_WORKSPACE/${{ env.REPORT_DIR }} python3 fossology/sources.py
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.REPORT_DIR }}/*
